const TosSeries = {
  "title": "Star Trek: The Original Series",
  "abbreviation": "TOS",
  "wrapperType": "collection",
  "collectionType": "TV Season",
  "artistId": 1439512969,
  "collectionId": 1439512970,
  "artistName": "Star Trek: The Original Series",
  "collectionName": "Star Trek: The Original Series, The Complete Series",
  "collectionCensoredName": "Star Trek: The Original Series, The Complete Series",
  "artistViewUrl": "https://itunes.apple.com/au/tv-show/star-trek-the-original-series-remastered/id1439512969?uo=4",
  "collectionViewUrl": "https://itunes.apple.com/au/tv-season/star-trek-the-original-series-remastered-the/id1439512970?uo=4",
  "artworkUrl60": "https://is3-ssl.mzstatic.com/image/thumb/Music118/v4/69/52/49/69524998-8243-f46c-e15b-454ac01a463a/source/60x60bb.jpg",
  "artworkUrl100": "https://is3-ssl.mzstatic.com/image/thumb/Music118/v4/69/52/49/69524998-8243-f46c-e15b-454ac01a463a/source/100x100bb.jpg",
  "collectionPrice": 44.99,
  "collectionHdPrice": 59.99,
  "collectionExplicitness": "notExplicit",
  "contentAdvisoryRating": "M",
  "trackCount": 79,
  "copyright": "© 2018 CBS Corp",
  "country": "AUS",
  "currency": "AUD",
  "releaseDate": "2018-11-09T08:00:00Z",
  "primaryGenreName": "Drama",
  "longDescription": "Space. The Final Frontier. The U.S.S. Enterprise embarks on a five year mission to explore the galaxy. The Enterprise is under the command of Captain James T. Kirk. The First Officer is Mr. Spock, from the planet Vulcan. The Chief Medical Officer is Dr. Leonard 'Bones' McCoy. Their mission is to explore strange new worlds, to seek new life and new civilizations, to boldly go where no man has gone before!",
  "seasons": [
    require(`./sttos/01.json`),
    require(`./sttos/02.json`),
    require(`./sttos/03.json`),
  ]
};
const TngSeries = {
  "title": "Star Trek: The Next Generation",
  "abbreviation": "TNG",
  "wrapperType": "collection",
  "collectionType": "TV Season",
  "artistId": 466420215,
  "collectionId": 1439415393,
  "artistName": "Star Trek: The Next Generation",
  "collectionName": "Star Trek: The Next Generation: The Complete Series",
  "collectionCensoredName": "Star Trek: The Next Generation: The Complete Series",
  "artistViewUrl": "https://itunes.apple.com/au/tv-show/star-trek-the-next-generation/id466420215?uo=4",
  "collectionViewUrl": "https://itunes.apple.com/au/tv-season/star-trek-the-next-generation-the-complete-series/id1439415393?uo=4",
  "artworkUrl60": "https://is2-ssl.mzstatic.com/image/thumb/Music128/v4/f1/ca/30/f1ca3025-15dc-bac1-6ead-97b9c06d3d41/source/60x60bb.jpg",
  "artworkUrl100": "https://is2-ssl.mzstatic.com/image/thumb/Music128/v4/f1/ca/30/f1ca3025-15dc-bac1-6ead-97b9c06d3d41/source/100x100bb.jpg",
  "collectionPrice": 99.99,
  "collectionHdPrice": 99.99,
  "collectionExplicitness": "notExplicit",
  "contentAdvisoryRating": "PG",
  "trackCount": 178,
  "copyright": "© 2018 CBS Corp",
  "country": "AUS",
  "currency": "AUD",
  "releaseDate": "2018-11-09T08:00:00Z",
  "primaryGenreName": "Sci-Fi & Fantasy",
  "longDescription": "Restored and meticulously remastered in brilliant high definition, <i>Star Trek: The Next Generation<\/i> is a true milestone in TV history. With such thought-provoking episodes as “The Measure of a Man” and “The Inner Light”; the return of the Borg in “The Best of Both Worlds”; and the time-shattering confrontation between Captain Jean-Luc Picard (Patrick Stewart) and the mysterious, god-like Q in the Hugo Award-winning series finale. Enjoy every memorable moment from the series that re-launched the Star Trek™ legacy for new “generations” to enjoy and experience!",
  "seasons": [
    require(`./sttng/01.json`),
    require(`./sttng/02.json`),
    require(`./sttng/03.json`),
    require(`./sttng/04.json`),
    require(`./sttng/05.json`),
    require(`./sttng/06.json`),
    require(`./sttng/07.json`),
  ]
};
const Ds9Series = {
  "title": "Star Trek: Deep Space Nine",
  "abbreviation": "DS9",
  "wrapperType": "collection",
  "collectionType": "TV Season",
  "artistId": 256033895,
  "collectionId": 1439412147,
  "artistName": "Star Trek: Deep Space Nine",
  "collectionName": "Star Trek: Deep Space Nine: The Complete Series",
  "collectionCensoredName": "Star Trek: Deep Space Nine: The Complete Series",
  "artistViewUrl": "https://itunes.apple.com/au/tv-show/star-trek-deep-space-nine/id256033895?uo=4",
  "collectionViewUrl": "https://itunes.apple.com/au/tv-season/star-trek-deep-space-nine-the-complete-series/id1439412147?uo=4",
  "artworkUrl60": "https://is5-ssl.mzstatic.com/image/thumb/Music118/v4/42/aa/ba/42aaba0c-ffef-7834-618b-93af2213b477/source/60x60bb.jpg",
  "artworkUrl100": "https://is5-ssl.mzstatic.com/image/thumb/Music118/v4/42/aa/ba/42aaba0c-ffef-7834-618b-93af2213b477/source/100x100bb.jpg",
  "collectionPrice": 79.99,
  "collectionExplicitness": "notExplicit",
  "contentAdvisoryRating": "M",
  "trackCount": 175,
  "copyright": "© 2018 CBS Corp",
  "country": "AUS",
  "currency": "AUD",
  "releaseDate": "2018-11-09T08:00:00Z",
  "primaryGenreName": "Sci-Fi & Fantasy",
  "longDescription": "The third Star Trek series concerns Benjamin Sisko, commander of the space station Deep Space Nine, who discovers the first known stable wormhole--a virtual shortcut through space that leads from the Alpha Quadrant to the Gamma Quadrant on the other side of the galaxy.",
  "seasons": [
    require(`./stds9/01.json`),
    require(`./stds9/02.json`),
    require(`./stds9/03.json`),
    require(`./stds9/04.json`),
    require(`./stds9/05.json`),
    require(`./stds9/06.json`),
    require(`./stds9/07.json`),
  ]
};
const VoySeries = {
  "title": "Star Trek: Voyager",
  "abbreviation": "VOY",
  "wrapperType": "collection",
  "collectionType": "TV Season",
  "artistId": 252478381,
  "collectionId": 1439413673,
  "artistName": "Star Trek: Voyager",
  "collectionName": "Star Trek: Voyager, The Complete Series",
  "collectionCensoredName": "Star Trek: Voyager, The Complete Series",
  "artistViewUrl": "https://itunes.apple.com/au/tv-show/star-trek-voyager/id252478381?uo=4",
  "collectionViewUrl": "https://itunes.apple.com/au/tv-season/star-trek-voyager-the-complete-series/id1439413673?uo=4",
  "artworkUrl60": "https://is4-ssl.mzstatic.com/image/thumb/Music118/v4/e9/9f/22/e99f22dc-ea9d-05bb-8729-4ff5172f22db/source/60x60bb.jpg",
  "artworkUrl100": "https://is4-ssl.mzstatic.com/image/thumb/Music118/v4/e9/9f/22/e99f22dc-ea9d-05bb-8729-4ff5172f22db/source/100x100bb.jpg",
  "collectionPrice": 79.99,
  "collectionExplicitness": "notExplicit",
  "contentAdvisoryRating": "M",
  "trackCount": 170,
  "copyright": "© 2018 CBS Corp",
  "country": "AUS",
  "currency": "AUD",
  "releaseDate": "2018-11-09T08:00:00Z",
  "primaryGenreName": "Sci-Fi & Fantasy",
  "longDescription": "Relive the journey of the starship Voyager - from its harrowing first season in the Delta Quadrant to its exciting encounters with alien life forms and its quest to return home. From internal ship conflicts to battles with the Borg Collective, \"Voyager\" represents some of the finest writing, acting and visual effects ever seen in the \"Trek\" universe.",
  "seasons": [
    require(`./stvoy/01.json`),
    require(`./stvoy/02.json`),
    require(`./stvoy/03.json`),
    require(`./stvoy/04.json`),
    require(`./stvoy/05.json`),
    require(`./stvoy/06.json`),
    require(`./stvoy/07.json`),
  ]
};
const EntSeries = {
  "title": "Star Trek: Enterprise",
  "abbreviation": "ENT",
  "wrapperType": "collection",
  "collectionType": "TV Season",
  "artistId": 212367634,
  "collectionId": 1439413076,
  "artistName": "Star Trek: Enterprise",
  "collectionName": "Star Trek: Enterprise: The Complete Series",
  "collectionCensoredName": "Star Trek: Enterprise: The Complete Series",
  "artistViewUrl": "https://itunes.apple.com/au/tv-show/star-trek-enterprise/id212367634?uo=4",
  "collectionViewUrl": "https://itunes.apple.com/au/tv-season/star-trek-enterprise-the-complete-series/id1439413076?uo=4",
  "artworkUrl60": "https://is4-ssl.mzstatic.com/image/thumb/Music118/v4/8f/c5/2c/8fc52c13-8d6b-6bde-f970-bfb69762e776/source/60x60bb.jpg",
  "artworkUrl100": "https://is4-ssl.mzstatic.com/image/thumb/Music118/v4/8f/c5/2c/8fc52c13-8d6b-6bde-f970-bfb69762e776/source/100x100bb.jpg",
  "collectionPrice": 59.99,
  "collectionHdPrice": 59.99,
  "collectionExplicitness": "notExplicit",
  "contentAdvisoryRating": "M",
  "trackCount": 98,
  "copyright": "© 2018 CBS Corp",
  "country": "AUS",
  "currency": "AUD",
  "releaseDate": "2018-11-09T08:00:00Z",
  "primaryGenreName": "Sci-Fi & Fantasy",
  "longDescription": "Join Captain Archer and his crew on their last adventures, including missions to restore the mind of the legendary Vulcan Surak to his people's High Command, to defeat a rogue army of genetically-enhanced supermen led by the brilliant Dr Soong, and as evil versions of themselves, to bring all the powers of Earth's Empite to heel in the Mirror Universe!",
  "seasons": [
    require(`./stent/01.json`),
    require(`./stent/02.json`),
    require(`./stent/03.json`),
    require(`./stent/04.json`),
  ]
};



export { TosSeries, TngSeries, Ds9Series, VoySeries, EntSeries };
